@hostDocker=localhost:80/api/auth
@hostVSC=localhost:8084


### GetById
GET http://{{hostVSC}}/login/2000000

### SignIn
POST http://{{hostDocker}}/signin/
Content-Type: application/json

{
  "id": "2000001",
  "password": "password"
}

### Characters
GET http://{{hostVSC}}/characters/2000001
Content-Type: application/json