@host1=localhost:80/api/auth
@host2=localhost:8084


### GetById
GET http://{{host2}}/login/2000000

### SignIn
POST http://{{host2}}/signin/
Content-Type: application/json

{
  "id": "2000001",
  "password": "password"
}
