@hostDocker=localhost:80/api/catalogs
@hostVSC=localhost:8084


### GetById
GET http://{{hostVSC}}/login/2000000

### SignIn
POST http://{{hostVSC}}/signin/
Content-Type: application/json

{
  "id": "2000001",
  "password": "password"
}
