@host=localhost:80


### Category
GET http://{{host}}/api/catalogs/categories
Content-Type: application/json

### Product
GET http://{{host}}/api/catalogs/products
Content-Type: application/json
