@host=localhost:8080


### Category
GET http://{{host}}/api/catalogs/api/category
Content-Type: application/json

### Product
GET http://{{host}}/api/catalogs/api/product
Content-Type: application/json
